apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-service
  namespace: springkubed-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: dashaun/io.springkubed.service.gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: "spring.cloud.vault.host"
              value: "vault.default.svc.cluster.local"
            - name: "spring.cloud.vault.port"
              value: "8200"
            - name: "spring.cloud.vault.enabled"
              value: "false"  