apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authorization-service
  namespace: springkubed-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "5"
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containers:
        - image: dashaun/io.springkubed.service.authorization:latest
          ports:
            - containerPort: 8080
          env:
            - name: "spring.cloud.vault.host"
              value: "vault.springkubed-io.knative.dashaun.cloud"
            - name: "spring.cloud.vault.port"
              value: "80"
