apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gateway-service
  namespace: springkubed-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: dashaun/io.springkubed.service.gateway:latest