apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vault
  namespace: springkubed-io
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: hashicorp/vault:latest
          ports:
            - containerPort: 8200